### ISSUE TITLE
Visualisation query

### ISSUE THREAD

**Issue by iqbal-lab** [michaelkyu/MobMess#1]
Hi there
(I know i'm asking for the moon on a stick but) is it feasible to auto-generate figures like Fig5C from your paper from the output of MobMess? Can you see a route for users to visualise Mobmess output and distinguish backbones from others?
regards
Zam

**Comment by michaelkyu** [comment]
Hi Zam, I do plan to release code that will visualize networks, as well as to show the explicit alignment of sequences (e.g. Fig 5D). I'll reply to this thread when the code becomes available. Stay tuned :)

Mike

**Comment by iqbal-lab** [comment]
Thanks, this will be v welcome!
